name: Cypress

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run: npx cypress run --headless

      - name: Set GitHub status
        uses: mikepenz/github-status-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          state: success
          description: Cypress tests passed
          context: cypress
